@startuml
top to bottom direction
skinparam CircledCharacterRadius 0
skinparam CircledCharacterFontSize 0
skinparam defaultFontSize 12
skinparam classFontSize 13
skinparam classFontStyle bold
skinparam ArrowFontSize 14
skinparam nodesep 80
skinparam ranksep 80

abstract class Uzivatel {
  id: int
  jmeno: String
  email: String
}

class Skladnik {
}

class VedouciSkladu {
}

class PrijemPohyb {
  dodavatel: String
  vytvoritPohyb(soucastka, mnozstvi)
}

class VydejPohyb {
  duvod: String
  vytvoritPohyb(soucastka, mnozstvi)
}

class PresunutiPohyb {
  zdrojLokaceId: int
  cilLokaceId: int
  vytvoritPohyb(soucastka, mnozstvi)
  zmenLokaci()
}

abstract class SkladovyPohyb {
  id: int
  datum: Date
  stav: String
  mnozstvi: int
  {abstract} vytvoritPohyb(soucastka, mnozstvi)
  overitData()
  provestPohyb()
}

class Projekt {
  id: int
  nazev: String
  priradSoucastku(Soucastka)
  odeberSoucastku(Soucastka)
}

class ProjektSoucastka {
  mnozstvi: int
}

class Sklad {
  id: int
  nazev: String
  najdiSoucastku(id): Soucastka
}

class Lokace {
  id: int
  oznaceni: String
}

class Soucastka {
  id: int
  nazev: String
  mnozstvi: int
  rezervovaneMnozstvi: int
  stav: String
  zvysMnozstvi(pocet)
  snizMnozstvi(pocet)
  rezervovat(pocet)
  zrusitRezervaci(pocet)
  overDostupnost(): boolean
}

' -- Generalizace: -down-|> = child ABOVE parent
PrijemPohyb    -down-|> SkladovyPohyb
VydejPohyb     -down-|> SkladovyPohyb
PresunutiPohyb -down-|> SkladovyPohyb
Skladnik       -down-|> Uzivatel
VedouciSkladu  -down-|> Uzivatel

' -- ProjektSoucastka (association class)
Projekt        "1"  --  ProjektSoucastka
ProjektSoucastka    ..> "1" Soucastka

' -- Kvalifikovana vazba
Sklad "[id: int]" -right-> "1" Soucastka : \nnajdiSoucastku

' -- Asociace
VedouciSkladu "1" -right-> "*" Projekt       : \nspravuje
Skladnik      "1" -right-> "*" SkladovyPohyb : \nvytváří
SkladovyPohyb "*"  -->     "1" Sklad         : \nmění stav
SkladovyPohyb "*"  -->     "1" Soucastka     : \nje součástí
Sklad         "1" *--      "*" Lokace        : \nobsahuje
Lokace        "1" o-right- "*" Soucastka     : \nukládá

@enduml
