@startuml
top to bottom direction

[*] --> Dostupna : Přidána do systému / mnozstvi = 0

Dostupna : do / overDostupnost()

' vnitřní přechody – jednorázové akce jako reakce na událost
Dostupna : naskladněno / zvysMnozstvi(pocet)
Dostupna : přiřazena k projektu / rezervovat(pocet)
Dostupna : odebrána z projektu / zrusitRezervaci(pocet)

' výdej: přechod nastane pouze pokud overDostupnost() = true
Dostupna --> Vydana   : výdej [overDostupnost()]
Dostupna --> Odepsana : odepsána [poškozena / zastaralá] / odepsat()

Vydana : entry / snizMnozstvi(pocet)
Vydana --> [*]

Odepsana --> [*]

@enduml
