@startuml
scale 1.5
skinparam defaultFontSize 13
skinparam ArrowThickness 1.5
skinparam ActivityBorderThickness 1.5
skinparam ActivityDiamondBorderThickness 1.5
skinparam ActivityBorderColor #444444
skinparam ActivityDiamondBorderColor #444444
skinparam ArrowColor #444444

start

:Zadat typ pohybu, součástku a množství;
:Inicializovat pohyb\n(SkladovyPohyb.vytvoritPohyb());
:Ověřit data pohybu\n(SkladovyPohyb.overitData());

if (Data platná?) then ([ano])
  :Provést pohyb\n(SkladovyPohyb.provestPohyb());

  ' split = rozdělení do větví s tlustou čárou (fork)
  split
    ' Větev 1 – příjem
    -> [typ == příjem];
    :Zvýšit množství na skladě\n(Soucastka.zvysMnozstvi(pocet));
  split again
    ' Větev 2 – výdej
    -> [typ == výdej];
    :Snížit množství na skladě\n(Soucastka.snizMnozstvi(pocet));
  split again
    ' Větev 3 – přesun
    -> [typ == přesun];
    :Ověřit dostupnost\n(Soucastka.overDostupnost());
    :Změnit lokaci součástky\n(PresunutiPohyb.zmenLokaci());
  end split
  ' end split = sloučení (join) – tlusté čáry

  :Potvrdit pohyb uživateli;

else ([ne])
  :Zamítnout pohyb;
endif

stop
@enduml
