@startuml
scale 1.5
skinparam defaultFontSize 13
skinparam ArrowThickness 1.5
skinparam ActivityBorderThickness 1.5
skinparam ActivityDiamondBorderThickness 1.5
skinparam ActivityBorderColor #444444
skinparam ActivityDiamondBorderColor #444444
skinparam ArrowColor #444444

start

:Zadat typ pohybu, součástku a množství;
:Inicializovat pohyb\n(SkladovyPohyb.vytvoritPohyb());
:Ověřit data pohybu\n(SkladovyPohyb.overitData());

if (Data platná?) then ([ano])
  :Provést pohyb\n(SkladovyPohyb.provestPohyb());

  fork
    if (typ == příjem?) then ([ano])
      :Zvýšit množství na skladě\n(Soucastka.zvysMnozstvi(pocet));
    else ([ne])
      if (typ == výdej?) then ([ano])
        :Snížit množství na skladě\n(Soucastka.snizMnozstvi(pocet));
      else ([ne – přesun])
        :Ověřit dostupnost\n(Soucastka.overDostupnost());
        :Změnit lokaci součástky\n(PresunutiPohyb.zmenLokaci());
      endif
    endif
  end fork

  :Potvrdit pohyb uživateli;

else ([ne])
  :Zamítnout pohyb;
endif

stop
@enduml
